site_name:            'Fathomable.io'
theme:
  name: material
  feature:
    tabs: true
markdown_extensions:
    - pymdownx.tasklist
    - pymdownx.striphtml:
        strip_comments: true
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
extra_css:
    - css/custom.css
extra:
  palette:
    primary:          'blue grey'
    accent:           'amber'
  logo:               'images/ttlogo.jpg'
site_favicon:         'images/favicon.ico'
site_author:          'Taylored Technology'
site_description:     'Federated Governance by Policy'
copyright:            'Taylored Technology 2016-Current'
pages:
  - 'Essentials': 'index.md'
  - 'Usage: Developer': 'usage-developer.md'
  - 'Usage: Govenor': 'usage-govenor.md'
  - 'Installing': 'installing.md'
  - 'Configuration':
    - 'Service': 'configuration/index.md'
    - 'Application': 'configuration/index.md'
    - 'Component': 'configuration/index.md'
    - 'Groups': 'configuration/groups.md'
    - 'Templates': 'configuration/templates.md'
