apiVersion: v1
kind: Service
metadata:
  name: fathomable
  namespace: kube-system
  labels:
    fathomable: fathomable
spec:
  selector:
    fathomable: fathomable
  ports:
    - name: api
      port: 3000
      targetPort: 3000
  sessionAffinity: None
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: fathomable
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fathomable
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: fathomable
    namespace: kube-system
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fathomable
  namespace: kube-system
  labels:
    fathomable: fathomable
spec:
  strategy:
    type: Recreate
  minReadySeconds: 10
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        fathomable: fathomable
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccount: fathomable
      securityContext:
        #runAsNonRoot: true
      volumes:
        - name: fathomable-config
          configMap:
            name: mandatory-fathomable-database
      containers:
        - name: fathomable
          image: gcr.io/taylored-technology/fathomable:kubernetes
          volumeMounts:
            - name: fathomable-config
              mountPath: /deploy
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: CLUSTER
              value: minikube
            - name: FQDN_BASE
              value: 'somewhere.co'
            - name: INGRESS_NGINX
              value: 'true'
            - name: AUTHENTICATOR
              value: 'amqk ef5z fvrn gp6q p7dg pq6g pncu ww7l'
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/alive
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mandatory-fathomable-database
  namespace: kube-system
data:
  db.json: ''
